### ISSUE TITLE
Errors and Bugs!

### ISSUE THREAD

**Issue by ghost** [failcoder/SVUI-Kit#1]
Alright well after throwing everything into the addon folder and resetting the saved variables for everything to do with SVUI as I get in game I'm getting errors and a few bugs which I will break down here.

I'll post bugs first and then errors at the end.

Bugs - 
Upon first loading into the game the installer for SVUI-kit will not come up, you have to go into the options to even initiate it.
I get a bunch of comic stuff ontop of my character and where the target of target is supposed to be and I'm unable to get rid of it nor move it.
even after setup/installing the UI the "Log" is still not docked correctly. 
[picture includes both errors above (comic stuff and "log")] http://i.imgur.com/qzwDpCp.jpg
Docklet background do not work as you can see I have it checked and I reloaded the UI and still no backgrounds for the docks.
http://i.imgur.com/r4OAUF5.jpg
In the inventory options screen you are unable to scroll down/up unless you resize or move the options screen first, oh and checkmarking the enable button does nothing at all (won't even stay checkmarked)
http://i.imgur.com/ftAFpWw.jpg
the Quest tracker options are completely missing.
http://i.imgur.com/Kx1iL6D.jpg
Themes options are completely missing as well like the quest tracker ones [not pictured as it's pretty much the same as the quest tracker one]
Plugins seems to be missing stuff as well (dunno if this is true yet or not as I dunno what plugins should be in there for this newer UI but I know the summery page is blank)
Item levels seems to be missing in the character info screen [I've reloaded and logged out and back in several times to test]
http://i.imgur.com/ZZnpIZh.png

Errors - 
these errors are kinda up in the wind on what initiated them exactly.

First error (happens upon login/reload) - 
6x ...eSVUI_Theme_Warcraft\SVUI_Theme_Warcraft-1.0.0.lua:156: attempt to index field 'Drunk' (a nil value)
...eSVUI_Theme_Warcraft\SVUI_Theme_Warcraft-1.0.0.lua:156: in main chunk

Locals:

---

Second error (dunno what initiated this one) - 

8x SVUI_Inventory\Loader.lua:435: attempt to call global 'tsort' (a nil value)
SVUI_Inventory\Loader.lua:435: in function `member'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:249: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:197>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1178: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1082: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1082: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1082: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1588: in function`FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1513: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1493>
(tail call): ?

[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
Accomplishment\Lib\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...Lib\AceGUI-3.0-34\widgets\AceGUIContainer-TreeGroup.lua:504: in function`SetSelected'
...Lib\AceGUI-3.0-34\widgets\AceGUIContainer-TreeGroup.lua:192: in function <...Lib\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:188>

Locals:
nil

---

Third error (happens upon mousing over/clicking the breakstuff docklet)
2x ...faceSVUI_Inventory\components\breakstuff.lua:225: attempt to index upvalue 'TTIP' (a nil value)
...faceSVUI_Inventory\components\breakstuff.lua:225: in function <...faceSVUI_Inventory\components\breakstuff.lua:208>

Locals:

Now these are all the few bugs and errors that I have gotten without heading out into the world, I'm unable to use the UI at the moment to test any further until at least a few (mainly the comic stuff being frozen on my screen) are fixed.

Oh and one more thing, how do I get rid of the item count info in the tooltip when you mouseover an item shows like 
[character]               [count]
[name of character]       [how much you have]
I have an addon that does this better and I wanna disable your version of it but I can't seem to find the option anywhere.

**Comment by failcoder** [comment]
This version is not ready for testing! I only posted a link for those who wanted to preview the code, which is still far from done.

**Comment by ghost** [comment]
Ah well that would make sense, thought you posting up the link meant that it was reading for some testing. My mistake

**Comment by failcoder** [comment]
All good. I should have this ready for testing in the next few days.

**Comment by failcoder** [comment]
A few comments I can make though:

-Most "Enable" type options are going away. This is due to each component now being its own addon. If for instance you did not want bags enabled then you would either disable the actual SVUI_Inventory addon, or remove it entirely from your addons folder.

-plugins aren't included just yet. I'll go into detail about these after testing begins.

-themes are still under heavy development, for the version you downloaded just disable their respective addons to avoid major issues

**Comment by ghost** [comment]
you misunderstood me on the bag/inventory thing, I want to use the bag/inventory addon because I don't like any of the other ones that are out there. I just want to disable one feature out of the bag/inventory and that is the item count info.
