### ISSUE TITLE
[Possible Missing] Windows popping up at 0,0 ccords for multi-monitor users [Closed]

### ISSUE THREAD

**Issue by TheBloodEagle** [failcoder/SVUI-Kit#10]
@failcoder I looked everywhere in case it is now an option, but with the new SVUI none of my pop up windows appear in the center of my center screen like you fixed with the old SVUI. 

Am I missing an option, or is it something that needs to be coded in again? I miss having everything pop up in the center rather than the far left of my left most monitor...

Thank you sir!

**Comment by TheBloodEagle** [comment]
I am not sure if you added it this last round, or in my excitement of the new version I just completely missed it, but I did not have the "Save Draggable Windows" check marked.

Regardless, please close this thread as it is working wonderfully again!

**Comment by failcoder** [comment]
Good deal!
