### ISSUE TITLE
installer error

### ISSUE THREAD

**Issue by Cromaxxx** [failcoder/SVUI-Kit#12]
when u click high resolution

1x SVUI_!Core\setup\installer.lua:315: attempt to index field 'Layout' (a nil value)
SVUI_!Core\setup\installer.lua:315: in function `?'
SVUI_!Core\setup\installer.lua:718: in function <SVUI_!Core\setup\installer.lua:710>

Locals:
self = <unnamed> {
 0 = <userdata>
 Left = <unnamed> {
 }
 Arg = "high"
 FuncName = "UserScreen"
 Right = <unnamed> {
 }
 Middle = <unnamed> {
 }
 texture = <unnamed> {
 }
}
fn = "UserScreen"
pairs = <function> defined =[C]:-1
SV = <table> {
 defaults = <table> {
 }
 UnregisterUpdate = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:659
 HexColor = <function> defined @SVUI_!Core\system\media.lua:404
 filterdefaults = <table> {
 }
 class = "WARRIOR"
 ResetData = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:973
 NewAnchor = <function> defined @SVUI_!Core\system\layout.lua:1192
 Skins = <table> {
 }
 CHAT_MSG_COMBAT_FACTION_CHANGE = <function> defined @SVUI_!Core\system\automations.lua:186
 RegisterFonts = <function> defined @SVUI_!Core\system\media.lua:610
 ___eventframe = <unnamed> {
 }
 PLAYER_REGEN_DISABLED = <function> defined @SVUI_!Core\system\core.lua:747
 QUEST_PROGRESS = <function> defined @SVUI_!Core\system\automations.lua:257
 ConfigurationMode = false
 ReLoad = <function> defined @SVUI_!Core\system\core.lua:790
 PreLoad = <function> defined @SVUI_!Core\system\core.lua:796
 ImportProfile = <function> defined @SVUI_!Core\system\core.lua:575
 Sounds = <table> {
 }
 GlobalFontList = <table> {
 }
 db = <table> {
 }
 Credits = "|cffff9900SUPERVILLAIN CREDITS:|r
|cff4f4f4f---------------------------------------------|r
|cffff9900CREATED BY:|r  S.Jackson
|cff4f4f4f---------------------------------------------|r
|cffff9900CODE GRANTS BY:|r  Azilroka, Sortokk, Kkthnx
|cff4f4f4f---------------------------------------------|r

|cffff9900SPECIAL THANKS TO:  |r|cfff81422Cairenn|r |cff2288cc(@WowInterface.com)|r  ..the most patient and accomodating person I know!

|cffff9900A VERY SPECIAL THANKS TO:  |r|cffffff00Movster|r  ..who inspired me to bring this project back to life!
|cff4f4f4f---------------------------------------------|r

|cffFFFF00THE HIGH COUNCIL  (aka EXECUTIVES):|r
|cff33FF33DOONGA|r - (The man who keeps me busy)
|cff33FF33PENGUINSANE|r - (The ace up my sleeve)
|cff4f4f4f---------------------------------------------|r

|cff99ff33KINGPINS  (aka INVESTORS):|r
Movster, Meggalo, Penguinsane, FaolanKing, Doonga
Cazart506, Moondoggy, Necroo, Chief Pullin, lkj61
BloodEagle, Egbert, Jerry Ferguson, Hyti, Elton
James Wats Reports = <table> {
 }
 Options = <table> {
 }
 Dock = <table> {
 }
 GetTheme = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:906
 ClassRole = "M"
 HasErrors = false
 Version = "1.0.0"
 TaintHandler = <function> defined @SVUI_!Core\system\core.lua:782
 DebugMode = true
 Timers = <table> {
 }
 UI_SCALE_CHANGED = <function> defined @SVUI_!Core\system\api.lua:1333
 Media = <table> {
 }
 ResetAnchors = <function> defined @SVUI_!Core\system\layout.lua:1208
 NewModule = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:921
 ConfigID = "SVUI_!Options"
 YOUR_HENCHMEN = <table> {
 }
 ToggleHenchman = <function> defined @SVUI_!Core\system\henchmen.lua:469
 AddonMessage = <function> defined @SVUI_!Core\system\core.lua:515
 Allegiance = "Alliance"
 Events = <table> {
 }
 RollFrames = <table> {
 }
 SpecialFX = <table> {
 }
 Inventory = <table> {
 }
 NoTexture = "SVUI_!Core\assets\textures\EMPTY"
 L = <table> {
 }
 AFK = SVUI_AFKFrame {
 }
 GameVersion = 60000
 AutoQuestProxy = <function> defined @SVUI_!Core\system\automations.lua:210
 VersionCheck = <function> defined @SVUI_!Core\system\core.lua:609
 Comix = SVUI_ComixFrame {
 }
 UnregisterEvent = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:618
 ResetFilter = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:1001
 ___loaded = true
 SetReversePoint = <function> defined @SVUI_!Core\system\utilit

**Comment by failcoder** [comment]
Fixed
