### ISSUE TITLE
Error on choosing unit frames

### ISSUE THREAD

**Issue by jguss87** [failcoder/SVUI-Kit#16]
Date: 2015-02-07 13:37:25
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\SVUI_!Core\setup\installer.lua line 508:
   attempt to index field 'Layout' (a nil value)
Debug:
   SVUI_!Core\setup\installer.lua:508: ?()
   SVUI_!Core\setup\installer.lua:718:
      SVUI_!Core\setup\installer.lua:710
Locals:
self = <table> {
 UnitframeLayout = <function> defined @Interface\AddOns\SVUI_!Core\setup\installer.lua:481
 CopyCustom = <function> defined @Interface\AddOns\SVUI_!Core\setup\presets.lua:1142
 Complete = <function> defined @Interface\AddOns\SVUI_!Core\setup\installer.lua:702
 ColorTheme = <function> defined @Interface\AddOns\SVUI_!Core\setup\installer.lua:455
 EZDefault = <function> defined @Interface\AddOns\SVUI_!Core\setup\installer.lua:585
 Auralayout = <function> defined @Interface\AddOns\SVUI_!Core\setup\installer.lua:568
 Minimalist = <function> defined @Interface\AddOns\SVUI_!Core\setup\installer.lua:639
 CopyPage = <function> defined @Interface\AddOns\SVUI_!Core\setup\presets.lua:1128
 GroupframeLayout = <function> defined @Interface\AddOns\SVUI_!Core\setup\installer.lua:518
 CopyPreset = <function> defined @Interface\AddOns\SVUI_!Core\setup\presets.lua:1114
 SelectTheme = <function> defined @Interface\AddOns\SVUI_!Core\setup\theme_select.lua:37
 UserScreen = <function> defined @Interface\AddOns\SVUI_!Core\setup\installer.lua:254
 ChatConfigs = <function> defined @Interface\AddOns\SVUI_!Core\setup\installer.lua:324
 CopyOnClick = <function> defined @Interface\AddOns\SVUI_!Core\setup\presets.lua:1135
 SetAllDefaults = <function> defined @Interface\AddOns\SVUI_!Core\setup\presets.lua:1110
 Install = <function> defined @Interface\AddOns\SVUI_!Core\setup\installer.lua:893
 BarLayout = <function> defined @Interface\AddOns\SVUI_!Core\setup\installer.lua:533
 Reset = <function> defined @Interface\AddOns\SVUI_!Core\setup\installer.lua:868
}
style = "super"
preserve = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = <table> {
 SVUI_TargetTarget_MOVE = "BOTTOMSVUIParentBOTTOM0182"
 BattleNetToasts_MOVE = "TOPRIGHTSVUIParentTOPRIGHT-4-250"
 SVUI_BossHolder_MOVE = "RIGHTSVUIParentRIGHT-1050"
 SVUI_Focus_MOVE = "BOTTOMSVUIParentBOTTOM310432"
 SVUI_TargetCastbar_MOVE = "BOTTOMSVUIParentBOTTOM278122"
 SVUI_Raid40_MOVE = "BOTTOMLEFTSVUIParentBOTTOMLEFT34.133334350586400"
 SVUI_Raid25_MOVE = "BOTTOMLEFTSVUIParentBOTTOMLEFT34.133334350586400"
 SVUI_StanceBar_MOVE = "BOTTOMRIGHTSVUI_ActionBar1TOPRIGHT04"
 SVUI_PetActionBar_MOVE = "BOTTOMLEFTSVUI_ActionBar1TOPLEFT04"
 SVUI_ActionBar5_MOVE = "BOTTOMRIGHTSVUI_ActionBar1BOTTOMLEFT-40"
 SVUI_Assist_MOVE = "TOPLEFTSVUIParentTOPLEFT34.133334350586-250"
 SVUI_Target_MOVE = "BOTTOMSVUIParentBOTTOM278182"
 SVUI_ActionBar2_MOVE = "BOTTOMSVUI_ActionBar1TOP0-2"
 SVUI_PlayerCastbar_MOVE = "BOTTOMSVUIParentBOTTOM-278122"
 SVUI_LootFrame_MOVE = "BOTTOMSVUIParentBOTTOM0350"
 SVUI_Raid10_MOVE = "BOTTOMLEFTSVUIParentBOTTOMLEFT34.133334350586400"
 SVUI_Tank_MOVE = "TOPLEFTSVUIParentTOPLEFT34.133334350586-175"
 GM_MOVE = "TOPLEFTSVUIParentTOPLEFT250-25"
 Tooltip_MOVE = "BOTTOMRIGHTSVUIParentBOTTOMRIGHT-284284"
 LoC_MOVE = "BOTTOMSVUIParentBOTTOM0350"
 SVUI_Party_MOVE = "BOTTOMLEFTSVUIParentBOTTOMLEFT34.133334350586400"
 SVUI_AltPowerBar_MOVE = "TOPSVUIParentTOP0-40"
 SVUI_ArenaHolder_MOVE = "RIGHTSVUIParentRIGHT-1050"
 SVUI_Player_MOVE = "BOTTOMSVUIParentBOTTOM-278182"
 SVUI_ThreatBar_MOVE = "BOTTOMRIGHTSVUIParentBOTTOMRIGHT-495182"
 SVUI_Raidpet_MOVE = "TOPLEFTSVUIParentTOPLEFT34.133334350586-325"
 SVUI_SpecialAbility_MOVE = "BOTTOMSVUIParentBOTTOM0370"
 SVUI_ActionBar3_MOVE = "BOTTOMLEFTSVUI_ActionBar1BOTTOMRIGHT40"
}
(_temporary) = nil
(*temporary) = "attempt to index field 'Layout' (a nil value)"
SV = <table> {
 defaults = <table> {
 }
 UnregisterUpdate = <function> defined @Interface\AddOns\SVUI_!Core\libs_SVUI_Lib\Registry.lua:659
 HexColor = <function> defined @Interface\AddOns\SVUI_!Core\system\media.lua:404
 filterdefaults = <table> {
 }
 class = "DEATHKNIGHT"
 ResetData = <function> defined @Interface\AddOns\SVUI_!Core\libs_SVUI_Lib\Registry.lua:973
 NewAnchor = <function> defined @Interface\AddOns\SVUI_!Core\system\layout.lua:1192
 Skins = <table> {
 }
 CHAT_MSG_COMBAT_FACTION_CHANGE = <function> defined @Interface\AddOns\SVUI_!Core\system\automations.lua:186
 RegisterF
AddOns:
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  AskMrRobot, v19
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSales, v5.21c.5521.5476(5.21c/embedded)
  AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
  AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
  AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
  AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
  AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
  AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
  AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
  AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
  AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
  AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
  AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
  AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
  AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
  AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
  AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
  AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
  Configator, v5.1.DEV.376(/embedded)
  DBMCore, v
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21c.5521 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21c.5521 (SanctimoniousSwamprat)
  GTFO, v4.35.9
  Informant, v5.21c.5521 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.363(/embedded)
  Recount, vv6.0.3j release
  SlideBar, v5.21c.5521 (SanctimoniousSwamprat)
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  SVUICore, v1.0.0
  SVUIActionBars, v1.0.0
  SVUIAuras, v1.0.0
  SVUIChat, v1.0.0
  SVUIInventory, v1.0.0
  SVUIMaps, v1.0.0
  SVUINamePlates, v1.0.0
  SVUIQuestTracker, v1.0.0
  SVUISkins, v1.0.0
  SVUITooltip, v1.0.0
  SVUIUnitFrames, v1.0.0
  SVUIThemeSimple, v1.0.0
  SVUIThemeWarcraft, v1.0.0
  TipHelper, v5.12.DEV.351(/embedded)
  ZygorGuidesViewer, v5.0
  BlizRuntimeLib_enUS v6.0.3.60000 <none>
  (ck=9a6)

**Comment by Cromaxxx** [comment]
also if they work they look strange http://i.imgur.com/JyKudLn.jpg

**Comment by failcoder** [comment]
Fixed
