### ISSUE TITLE
[Question] about Simple Theme in this newest build

### ISSUE THREAD

**Issue by TheBloodEagle** [failcoder/SVUI-Kit#18]
I noticed with the new build this morning that when I set the theme to Simple, that instead of the backgrounds being a straight transparent black, they now have the background of Vintage, with class and con colors.

Is this intentional for Simple theme, have I messed up something somewhere, or is it just a bug?

**Comment by failcoder** [comment]
Check again and let me know if they are appearing correctly.

**Comment by TheBloodEagle** [comment]
All of the windows like character pane and inventory are now working correctly, but the unit frames still have a latticework background behind them that is colored by class or reaction.

I attempted to remove this by going into the Unit Frames general settings and setting both background dropdowns to "none" without success. I also attempted to set my Theme to another, then back to simple, also without success.

In order to keep the unit frames with the same sleek transparent black look, are you supposed to not choose anything during the install process when it asks you to choose a look and feel?

**Comment by failcoder** [comment]
This should be more consistent now, still need to add theme specific color schemes for the installer

**Comment by TheBloodEagle** [comment]
Any chance the theme specific color for the simple theme unit frames can be the same black translucence as the rest of the theme?

**Comment by failcoder** [comment]
This issue was moved to failcoder/Supervillain_UI#92
