### ISSUE TITLE
Friends list-datatext

### ISSUE THREAD

**Issue by helgard24** [failcoder/SVUI-Kit#19]
Hello, just wanted to bring to attention a minor issue i have noticed (even on current live version).
when hovering over the friends datatext,  my real ID friends dont show 100% correctly.
what i mean is: it will show their character, but not their level, as it should, and sometimes doesnt properly color their character, based on class...

yet some of the friends will show these things properly on real ID...  and it changes always, its completely random, who is proper and not..

also, when right clicking to bring up the invite section, it doesnt bring up all my real ID characters as they should, to invite (because they are not being shown correctly)

and is there an option, or something to change how the absorbs show, on health bars?   when health diminishes (from right to left)  and i throw up bubbles,  the absorbs show on the far left side of screen, (not right side, where they should be)

**Comment by failcoder** [comment]
I will look into it

**Comment by failcoder** [comment]
This issue was moved to failcoder/Supervillain_UI#93
