### ISSUE TITLE
vendor greys+auto repair

### ISSUE THREAD

**Issue by Cromaxxx** [failcoder/SVUI-Kit#20]
still doesn't work

**Comment by failcoder** [comment]
I'll look again but so far it's working for me as expected.

**Comment by Cromaxxx** [comment]
also skin for adibags is not working properly because when some element is open where bags are its always element on top and you cant click neither element nor bag items

**Comment by Cromaxxx** [comment]
y strange i did delete everything 5 mins ago and downloaded fresh zip but it doesnt work also i tried tick and untick there's no error but it doesnt work.. i'll tinker after the raid with it

**Comment by penguinsane** [comment]
Working as intended for me as well. Tested repair, guild repair, and vendor greys.

**Comment by failcoder** [comment]
Does AdiBags have an auto-vendor/repair function?

**Comment by Cromaxxx** [comment]
nope.. its just another issue so i didnt want to spam issues

**Comment by failcoder** [comment]
updated, try now

**Comment by Cromaxxx** [comment]
i tried /sv reset, deleting folders, disabling addons, deleting luas of svui doesnt work.. it works on bags when i disabled adibags and auto repair doesnt work still..

**Comment by Cromaxxx** [comment]
when i did sv reset i got error and this screen http://imgur.com/xxuNtX9

3x SVUI_Auras\SVUI_Auras-1.0.0.lua:300: Usage: UnitClass("unit")
[C]: in function `UnitClass'
SVUI_Auras\SVUI_Auras-1.0.0.lua:300: in function <SVUI_Auras\SVUI_Auras.lua:283>
SVUI_Auras\SVUI_Auras-1.0.0.lua:351: in function`ToggleConsolidatedBuffs'
SVUI_Auras\SVUI_Auras-1.0.0.lua:431: in function `RoleChangedCallback'
SVUI_!Core\system\utilities.lua:170: in function`PlayerInfoUpdate'
SVUI_!Core\system\core.lua:792: in function `Initialize'
SVUI_!Core\libs_SVUI_Lib\Registry.lua:912: in function <SVUI_!Core\libs\_SVUI_Lib\Registry.lua:851>

Locals:
self = nil
event = nil
arg = nil
name = "Sanctity Aura"
_ = nil
duration = nil
expiration = nil
spellId = 167187
slot = 16
caster = nil
(for index) = 9
(for limit) = 9
(for step) = 1
i = 9
buff = <unnamed> {
 0 = <userdata>
 empty = <unnamed> {
 }
 bg = <unnamed> {
 }
 bar = <unnamed> {
 }
}
MOD = <table> {
 UnregisterUpdate = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:630
 media = <table> {
 }
 ChangeDBVar = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:523
 UpdateAuraHeader = <function> defined @SVUI_Auras\SVUI_Auras.lua:436
 TitleID = "Auras"
 CreateIcon = <function> defined @SVUI_Auras\SVUI_Auras.lua:210
 RegisterUpdate = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:614
 private = <table> {
 }
 ___eventframe = <unnamed> {
 }
 Load = <function> defined @SVUI_Auras\SVUI_Auras.lua:526
 LoadOptions = <function> defined @SVUI_Auras\Loader.lua:187
 initialized = false
 NameID = "SVUI [Auras]"
 UpdateAuraHolder = <function> defined @SVUI_Auras\SVUI_Auras.lua:495
 RegisterEvent = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:569
 Update_ConsolidatedBuffsSettings = <function> defined @SVUI_Auras\SVUI_Auras.lua:384
 Holder = SVUI_AurasAnchor {
 }
 ToggleConsolidatedBuffs = <function> defined @SVUI_Auras\SVUI_Auras.lua:338
 HyperBuffFrame = SVUI_ConsolidatedBuffs {
 }
 ReLoad = <function> defined @SVUI_Auras\SVUI_Auras.lua:515
 Version = "1.0.0"
 public = <table> {
 }
 LoD = false
 UnregisterEvent = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:589
 CombatLocked = false
 Schema = "Auras"
}
ConsolidatedBuff_OnUpdate = <function> defined @SVUI_Auras\SVUI_Auras.lua:251

and this screen http://imgur.com/xxuNtX9

**Comment by Cromaxxx** [comment]
after update again same error and screen still no auto repair nor auto vendor greys

**Comment by Cromaxxx** [comment]
k after reload vendor greys +auto repair works just i got this http://imgur.com/hXNdlZJ

**Comment by failcoder** [comment]
Fixed

**Comment by Cromaxxx** [comment]
k i tested it u can close it /sv reset and reloading profile works now normally

**Comment by failcoder** [comment]
Sweet deal!
