### ISSUE TITLE
[Suggestion] Razer Naga-friendly layout option

### ISSUE THREAD

**Issue by penguinsane** [failcoder/SVUI-Kit#21]
It's not particularly hard to adjust action bars or unit frames, but it would be nice if a Naga-friendly option was available.

Could look something like: http://puu.sh/fErcF/97eb421334.jpg
With movers up: http://puu.sh/fErXN/f7f70ff857.jpg

The two action bars in the middle need to be anchored to top-left if done this way, btw.

Just an idea. I always have to change this stuff around after every update, it's no big deal, but I know this bar layout is semi-popular with a lot of Naga/G600 users.

**Comment by failcoder** [comment]
Sounds handy, I will add it to my list.

**Comment by failcoder** [comment]
This issue was moved to failcoder/Supervillain_UI#94
