### ISSUE TITLE
[Bug] Versatility often doesn't display who cast it

### ISSUE THREAD

**Issue by penguinsane** [failcoder/SVUI-Kit#22]
Should look like this: http://puu.sh/fEsOD/37ede190ac.jpg

Usually looks like this: http://puu.sh/fEsSv/37a6c31667.jpg

**Comment by failcoder** [comment]
fixed

**Comment by failcoder** [comment]
Fixed again, I screwed up this change and it was causing UnitClass to fail :(

**Comment by failcoder** [comment]
Confirmed?

**Comment by penguinsane** [comment]
Sorry! Yes, looks like it's fixed, but it displays the name of the pet instead of the hunter if they're the ones providing Versatility.

Also, Trueshot Aura (Attack Power)  doesn't say that it is cast by me on my hunter, but I was not in a group at the time so that may be why.

**Comment by failcoder** [comment]
This issue was moved to failcoder/Supervillain_UI#95
