### ISSUE TITLE
[Bug] Some menu skins aren't skinned right away

### ISSUE THREAD

**Issue by penguinsane** [failcoder/SVUI-Kit#23]
Very minor issue. Sometimes skins don't load right away, such as dropdown menus, until clicked on and off again. Default install of new SVUI.

http://puu.sh/fEtgf/0dea972670.jpg

**Comment by failcoder** [comment]
By default did you also delete all the Interface folders? (pretty much anything but "AddOns")

**Comment by penguinsane** [comment]
I did, yeah. Wiped out everything SVUI and was fresh install.

**Comment by failcoder** [comment]
Thats why, the Interface textures were a failsafe for textures that Blizzard slips by me.

**Comment by failcoder** [comment]
Im still working out how to handle these without resorting to brute force images.

**Comment by penguinsane** [comment]
I thought it might be something like that. Good luck with finding a solution!

**Comment by failcoder** [comment]
This issue was moved to failcoder/Supervillain_UI#96
