### ISSUE TITLE
Graphic errors in latest commit

### ISSUE THREAD

**Issue by qmod** [failcoder/SVUI-Kit#24]
With latest commit f5f5cd276338145c0dff9fd1c4b6f409ee2e3c2a

Seeing this error on login, with various crit "bam" "kapow" mini graphics on the screen at all times

Also Henchman options button on bottom right is no longer there.

1x SVUI_Auras\SVUI_Auras-1.0.0.lua:300: Usage: UnitClass("unit")
[C]: in function `UnitClass'
SVUI_Auras\SVUI_Auras-1.0.0.lua:300: in function <SVUI_Auras\SVUI_Auras.lua:283>
SVUI_Auras\SVUI_Auras-1.0.0.lua:351: in function`ToggleConsolidatedBuffs'
SVUI_Auras\SVUI_Auras-1.0.0.lua:431: in function `RoleChangedCallback'
SVUI_!Core\system\utilities.lua:170: in function`PlayerInfoUpdate'
SVUI_!Core\system\core.lua:792: in function `Initialize'
SVUI_!Core\libs_SVUI_Lib\Registry.lua:912: in function <SVUI_!Core\libs\_SVUI_Lib\Registry.lua:851>

Locals:
self = nil
event = nil
arg = nil
name = "Inspiring Presence"
_ = nil
duration = nil
expiration = nil
spellId = 167188
slot = 22
caster = nil
(for index) = 9
(for limit) = 9
(for step) = 1
i = 9
buff = <unnamed> {
 0 = <userdata>
 empty = <unnamed> {
 }
 bg = <unnamed> {
 }
 bar = <unnamed> {
 }
}
MOD = <table> {
 UnregisterUpdate = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:630
 media = <table> {
 }
 ChangeDBVar = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:523
 UpdateAuraHeader = <function> defined @SVUI_Auras\SVUI_Auras.lua:436
 TitleID = "Auras"
 CreateIcon = <function> defined @SVUI_Auras\SVUI_Auras.lua:210
 RegisterUpdate = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:614
 private = <table> {
 }
 ___eventframe = <unnamed> {
 }
 Load = <function> defined @SVUI_Auras\SVUI_Auras.lua:526
 LoadOptions = <function> defined @SVUI_Auras\Loader.lua:187
 initialized = false
 NameID = "SVUI [Auras]"
 UpdateAuraHolder = <function> defined @SVUI_Auras\SVUI_Auras.lua:495
 RegisterEvent = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:569
 Update_ConsolidatedBuffsSettings = <function> defined @SVUI_Auras\SVUI_Auras.lua:384
 Holder = SVUI_AurasAnchor {
 }
 ToggleConsolidatedBuffs = <function> defined @SVUI_Auras\SVUI_Auras.lua:338
 HyperBuffFrame = SVUI_ConsolidatedBuffs {
 }
 ReLoad = <function> defined @SVUI_Auras\SVUI_Auras.lua:515
 Version = "1.0.0"
 public = <table> {
 }
 LoD = false
 UnregisterEvent = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:589
 CombatLocked = false
 Schema = "Auras"
}
ConsolidatedBuff_OnUpdate = <function> defined @SVUI_Auras\SVUI_Auras.lua:251

**Comment by failcoder** [comment]
Fixed
