### ISSUE TITLE
[request] 2 options that would be nice...

### ISSUE THREAD

**Issue by ghost** [failcoder/SVUI-Kit#3]
what needs to be options are in the pictures below.

Map cords on the big map are out of place so either needs to be moved, or have an option to at least let the player move or remove it. (couldn't find an option at all)
http://i.imgur.com/KquOgjj.jpg

Item count needs to have an option to be removed, my tooltip is already cluttered by some other addons + I have a addon that does the item count better than yours. (again couldn't find an option at all to do this)
http://i.imgur.com/fkdFm59.jpg

**Comment by failcoder** [comment]
Both are added now.

**Comment by ghost** [comment]
Cool, though you ended up making another issue with the world map cords now lol. If you disable them it still semi-shows up on the map even after a reload. 

Youtube vid below, couldn't seem to upload it anywhere else lol :/
http://youtu.be/VqU4eccog8g

**Comment by failcoder** [comment]
Fixed, I think. Try this update.

**Comment by ghost** [comment]
Yep yep all fixed now, I'm closing this issue.
