### ISSUE TITLE
[Bug] Chat window font size resetting

### ISSUE THREAD

**Issue by TheBloodEagle** [failcoder/SVUI-Kit#30]
Each time you switch characters or reload your UI, all of the Chat window font sizes reset to your default.

**Comment by qmod** [comment]
Since this issue was regarding chat, just posting two related bugs here with some more detail.

When changing font by right clicking the "General" tab, getting this error:

2x SVUI_Chat\SVUI_Chat-1.0.0.lua:1061: attempt to index field 'chatdialog' (a string value)
SVUI_Chat\SVUI_Chat-1.0.0.lua:1061: in function <SVUI_Chat\SVUI_Chat.lua:1054>
[C]: in function `func'
FrameXML\UIDropDownMenu.lua:748: in function`UIDropDownMenuButton_OnClick'
[string "_:OnClick"]:1: in function <[string "_:OnClick"]:1>

Locals:
(*temporary) = <function> defined =[C]:-1
 = <function> defined @FrameXML\FloatingChatFrame.lua:940
 = <function> defined @SVUI_Chat\SVUI_Chat.lua:1054

**Comment by qmod** [comment]
And when clicking CHAT in the SVUI options menu, getting this error:

2x SVUI_Chat\Loader.lua:169: attempt to get length of global 'a' (a nil value)
SVUI_Chat\Loader.lua:169: in function `member'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:249: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:197>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1145: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1082: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1588: in function`FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1513: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1493>
(tail call): ?

[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
TomTom\libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...ibs\AceGUI-3.0-34\widgets\AceGUIContainer-TreeGroup.lua:504: in function`SetSelected'
...ibs\AceGUI-3.0-34\widgets\AceGUIContainer-TreeGroup.lua:192: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:188>

Locals:
nil

**Comment by penguinsane** [comment]
```
1x SVUI_Chat\Loader.lua:169: attempt to get length of global 'a' (a nil value)
SVUI_Chat\Loader.lua:169: in function `member'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:249: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:197>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1145: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1082: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1588: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:1513: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1493>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...faceAltoholic\libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...ibs\AceGUI-3.0-34\widgets\AceGUIContainer-TreeGroup.lua:504: in function `SetSelected'
...ibs\AceGUI-3.0-34\widgets\AceGUIContainer-TreeGroup.lua:192: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:188>

Locals:
nil
```

**Comment by TheBloodEagle** [comment]
My issue has been fixed and is working great!
