### ISSUE TITLE
[Bug] Misalignment of graphics

### ISSUE THREAD

**Issue by TheBloodEagle** [failcoder/SVUI-Kit#31]
When receiving items from your Garrison cache or work orders, the background is in the usual place, but the icon and text are about 4 inches lower in the middle of the screen.

**Comment by lownignitus** [comment]
I have the same issue, and here is a screen cap of it: http://imgur.com/YsLUKHl

**Comment by TheBloodEagle** [comment]
Issue has been fixed for me!
