### ISSUE TITLE
[Bug] Themes do not work now...

### ISSUE THREAD

**Issue by ghost** [failcoder/SVUI-Kit#32]
so just updated to commit e2312a19dd288303e3a2cda2f1b4a9a538505189 and themes do not work now, when I logged into the game I was set back to the default theme that it's set to when first loading up the UI and upon trying to choose the simple or warcraft theme and reloading my UI I am still stuck on the default theme with no changes what so ever. No errors are coming through whats so ever as well so can't say for sure what is causing this.

**Comment by ghost** [comment]
This is still an issue in commit 2434dc9792a8fcdee85a04eabac0c3660508cdef

**Comment by failcoder** [comment]
Fixed

**Comment by ghost** [comment]
Yep this is fixed, closing the issue
