### ISSUE TITLE
[Bug?] Healer Raidframes, player power bar not showing despite option

### ISSUE THREAD

**Issue by penguinsane** [failcoder/SVUI-Kit#34]
Using "Healer" option, have option chosen but it's still not showing player power bars.

http://puu.sh/fLwOp/c1e560e662.jpg

**Comment by failcoder** [comment]
This should be working now

**Comment by penguinsane** [comment]
Confirmed on "Display Frames" test, haven't gotten in an actual group yet to make sure it's working there. Thank you!

**Comment by penguinsane** [comment]
Yup, working in actual groups. Thanks a bunch!
