### ISSUE TITLE
in TK

### ISSUE THREAD

**Issue by Nyrin** [failcoder/SVUI-Kit#42]
Message: ...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:543: script ran too long
Time: 02/13/15 13:41:36
Count: 1
Stack: ...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:543: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:18: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>

...nterface\AddOns\SVUI_Skins\components\addons\DBM.lua:155: in function <...nterface\AddOns\SVUI_Skins\components\addons\DBM.lua:143>
[C](?): in function `AddBoss'
Interface\AddOns\DBM-Core\DBM-Core.lua:4782: in function`StartCombat'
Interface\AddOns\DBM-Core\DBM-Core.lua:4523: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:4518>
(tail call): ?
Interface\AddOns\DBM-Core\DBM-Core.lua:561: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:548>

Locals: message = "...nterface\AddOns\SVUI_Skins\components\addons\DBM.lua:155: attempt to index global 'DBM_SavedOptions' (a nil value)"
warnType = nil
keepHidden = nil
stack = "...nterface\AddOns\SVUI_Skins\components\addons\DBM.lua:155: in function <...nterface\AddOns\SVUI_Skins\components\addons\DBM.lua:143>
[C](?): in function `AddBoss'
Interface\AddOns\DBM-Core\DBM-Core.lua:4782: in function`StartCombat'
Interface\AddOns\DBM-Core\DBM-Core.lua:4523: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:4518>
(tail call): ?
Interface\AddOns\DBM-Core\DBM-Core.lua:561: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:548>
"
messageStack = "...nterface\AddOns\SVUI_Skins\components\addons\DBM.lua:155: attempt to index global 'DBM_SavedOptions' (a nil value)...nterface\AddOns\SVUI_Skins\components\addons\DBM.lua:155: in function <...nterface\AddOns\SVUI_Skins\components\addons\DBM.lua:143>
[C](?): in function `AddBoss'
Interface\AddOns\DBM-Core\DBM-Core.lua:4782: in function`StartCombat'
Interface\AddOns\DBM-Core\DBM-Core.lua:4523: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:4518>
(tail call): ?
Interface\AddOns\DBM-Core\DBM-Core.lua:561: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:548>
"
index = 1
(_temporary) = <table> {
}
(_temporary) = "count = 1
bar = DBM_BossHealth_Bar_1 {
 0 = <userdata>
 nameused = true
 id = 19622
 hidden = false
 value = 100
}
background = DBM_BossHealth_Bar_1BarBorder {
 0 = <userdata>
}
progress = DBM_BossHealth_Bar_1Bar {
 0 = <userdata>
}
name = DBM_BossHealth_Bar_1BarName {
 0 = <userdata>
}
timer = DBM_BossHealth_Bar_1BarTimer {
 0 = <userdata>
}
prev = nil
_ = "TOP"
anch = DBMBossHealth {
 0 = <userdata>
 styled = true
}
_ = "BOTTOM"
_ = 0
_ = 0
(_temporary) = nil
(_temporary) = DBM_BossHealth_Bar_1 {
 0 = <userdata>
 nameused = true
 id = 19622
 hidden = false
 value = 100
}
(_temporary) = <userdata>
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = "attempt to index global 'DBM_SavedOptions' (a nil value)"
_G = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined (_temporary) = 4
(_temporary) = "script ran too long"
_ScriptErrorsFrame = ScriptErrorsFrame {
 0 = <userdata>
 warnType = <table> {
 }
 messages = <table> {
 }
 close = <unnamed> {
 }
 previous = <unnamed> {
 }
 indexLabel = <unnamed> {
 }
 locals = <table> {
 }
 title = <unnamed> {
 }
 times = <table> {
 }
 seen = <table> {
 }
 count = <table> {
 }
 order = <table> {
 }
 next = <unnamed> {
 }
}

**Comment by failcoder** [comment]
Fixed
