### ISSUE TITLE
[Bug] Frame taint issues; dungeon journal, AH, mail

### ISSUE THREAD

**Issue by penguinsane** [failcoder/SVUI-Kit#44]
Sometimes when playing for a bit, it's like the frames get tainted and can't be clicked. The most noticeable place this happens is the dungeon/raid journal, but it also happens with the AH and mailbox (though I have only noticed the AH/mailbox taint when TradeSkillMaster is installed). 

No error is reported when this happens.

Additionally, sometimes when this happens, tooltips stop showing up in UI elements, like the character pane.

This issue has been around for quite some time.

**Comment by failcoder** [comment]
Just made an adjustment that should hopefully relieve this issue.

**Comment by penguinsane** [comment]
Tentatively saying it's fixed. So far no issues.

Mouseover on player buffs doesn't seem to work now, though. Just updated prior to this comment.

**Comment by failcoder** [comment]
Mouse over, fixed

**Comment by penguinsane** [comment]
Sorry for the late response. Everything looks okay from here, closing unless something pops up again. :) Thank you!

**Comment by penguinsane** [comment]
Happening again after today's updates: http://puu.sh/gbAor/c590cd162d.jpg
None of the bosses can be selected to view their abilities, AH sometimes goes gray, as does mail.

**Comment by failcoder** [comment]
Just updated curse. Try the latest

**Comment by penguinsane** [comment]
Looks good so far, closing again. Thanks for the fast update!
