### ISSUE TITLE
[Bug] Follower panel sometimes loses info

### ISSUE THREAD

**Issue by penguinsane** [failcoder/SVUI-Kit#45]
After a while of playing, my follower panel eventually does this: 

http://puu.sh/fTgFR/5788ff50e5.jpg

Loses ability to view abilities/traits, goes blank.

**Comment by failcoder** [comment]
Somehow I feel like this may be tied to #44

**Comment by penguinsane** [comment]
Should be fixed with #44 now, closing! Will report if I see it again.

**Comment by penguinsane** [comment]
Happening again after today's updates: http://puu.sh/gbAor/c590cd162d.jpg
