### ISSUE TITLE
Iinstallation error

### ISSUE THREAD

**Issue by oompaloomp** [failcoder/SVUI-Kit#46]
Good day
No found benefit for installation.
From the folder \SVUI-Kit-master\ put all the folders in the => \Interface\ AddOns\
in result:
http://i.imgur.com/ws2RVMg.jpg
What did I do wrong?

**Comment by oompaloomp** [comment]
With the installation of figured out, now another problem:
http://i.imgur.com/sFeBCmt.jpg
SVUI [DEBUG]: SVMap [Load] - (02/14/15 19:39:16) Interface\AddOns\SVUI\packages\map\SVMap.lua:299: attempt to index field 'playerXCoords' (a nil value)
SVUI [DEBUG]: SVHenchmen [Load] - (02/14/15 19:39:17) Interface\AddOns\SVUI_!Core\system\ [dock.lua:758] : attempt to index field 'private' (a nil value)
SVUI [DEBUG]: SVTools [Load] - (02/14/15 19:39:17) Interface\AddOns\SVUI_!Core\system\ [dock.lua:758] : attempt to index field 'private' (a nil value)
SVUI [DEBUG]: SVQuest [Load] - (02/14/15 19:39:17) Interface\AddOns\SVUI_!Core\system\ [dock.lua:758] : attempt to index field 'private' (a nil value)
SVUI [DEBUG]: StyleOMatic [Load] - (02/14/15 19:39:17) ...terface\AddOns\SVUI_StyleOMatic\ [SVUI_StyleOMatic.lua:519] : attempt to index field 'Media' (a nil value)
SVUI [DEBUG]: SVMap [Load] - (02/14/15 19:39:17) Interface\AddOns\SVUI\packages\map\ [SVMap.lua:299] : attempt to index field 'playerXCoords' (a nil value)
Very difficult to run the game

**Comment by failcoder** [comment]
You still have the original SVUI addon installed. You must delete all addon folders before using this test version

**Comment by oompaloomp** [comment]
BTW when i installing just all folders from \SVUI-Kit-master\ put all the folders in the => \Interface\ AddOns\
in result:
http://i.imgur.com/ws2RVMg.jpg
How i can installed rightly?

**Comment by oompaloomp** [comment]
*rightly

**Comment by failcoder** [comment]
I would start by deleting all other addons.

**Comment by oompaloomp** [comment]
Huh, worked, thanks.
