### ISSUE TITLE
Getting mail

### ISSUE THREAD

**Issue by Nyrin** [failcoder/SVUI-Kit#5]
Message: Interface\AddOns\SVUI_!Core\system\mail.lua:85: attempt to call global 'OpenMailItem' (a nil value)
Time: 02/05/15 11:11:27
Count: 1
Stack: Interface\AddOns\SVUI_!Core\system\mail.lua:85: in function <Interface\AddOns\SVUI_!Core\system\mail.lua:77>

Locals: (_temporary) = nil
(_temporary) = 7
(_temporary) = 7
(_temporary) = "attempt to call global 'OpenMailItem' (a nil value)"
baseInboxFrame_OnClick = <function> defined @Interface\FrameXML\MailFrame.lua:263
InboxFrame_OnClick = <function> defined @Interface\AddOns\SVUI_!Core\system\core.lua:530
SV = <table> {

**Comment by failcoder** [comment]
This has been fixed
