### ISSUE TITLE
[Error]

### ISSUE THREAD

**Issue by Nyrin** [failcoder/SVUI-Kit#54]
Message: AceLocale-3.0: Broker_Garrison: Missing entry for 'Notification'
Time: 02/15/15 11:53:58
Count: 1
Stack: Interface\AddOns\Broker_Garrison\config.lua:1491: in function `getDataOptionTable'
Interface\AddOns\Broker_Garrison\config.lua:1634: in function`SetupOptions'
Interface\AddOns\Broker_Garrison\core.lua:1808: in function <Interface\AddOns\Broker_Garrison\core.lua:1750>
(tail call): ?

[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...s\Broker_Garrison\Libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...s\Broker_Garrison\Libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...s\Broker_Garrison\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

**Comment by failcoder** [comment]
Not an SVUI error

**Comment by Nyrin** [comment]
Ooops my bad.
