### ISSUE TITLE
this happend when i logged in.

### ISSUE THREAD

**Issue by Nyrin** [failcoder/SVUI-Kit#6]
ID: 1
Error occured in: Global
Count: 1
Message: ...face\AddOns\SVUI_!Core\system_docklets\garrison.lua line 110:
attempt to call method 'StartAlert' (a nil value)
Debug:
...face\AddOns\SVUI_!Core\system_docklets\garrison.lua:110:
...face\AddOns\SVUI_!Core\system_docklets\garrison.lua:94
Locals:
self = SVUI_Garrison {
0 = <userdata>
Activate = <function> defined @Interface\AddOns\SVUI_!Core\system\dock.lua:472
Parent = SVUI_DockBarBottomLeft {
}
GetMenuList = <function> defined @Interface\AddOns\SVUI_!Core\system\dock.lua:622
UpdateBackdrop = <function> defined @Interface\AddOns\SVUI_!Core\system\api.lua:459
Deactivate = <function> defined @Interface\AddOns\SVUI_!Core\system\dock.lua:485
SetBackdropBorderColor = <function> defined =[C]:-1
Icon = <unnamed> {
}
hover = <unnamed> {
}
pushed = <unnamed> {
}
Sparks = <unnamed> {
}
ClickTheme = <function> defined @Interface\AddOns\SVUITheme_Warcraft\SVUITheme_Warcraft.lua:58
CustomTooltip = <function> defined @Interface\AddOns\SVUI_!Core\system_docklets\garrison.lua:222
SetFrameLevel = <function> defined =[C]:-1
Panel = <unnamed> {
}
MakeDefault = <function> defined @Interface\AddOns\SVUI_!Core\system\dock.lua:464
OrderIndex = 1
BackdropNeedsUpdate = true
}
event = "GARRISON_MISSION_FINISHED"
(_temporary) = nil
(_temporary) = SVUI_Garrison {
0 = <userdata>
Activate = <function> defined @Interface\AddOns\SVUI_!Core\system\dock.lua:472
Parent = SVUI_DockBarBottomLeft {
}
GetMenuList = <function> defined @Interface\AddOns\SVUI_!Core\system\dock.lua:622
UpdateBackdrop = <function> defined @Interface\AddOns\SVUI_!Core\system\api.lua:459
Deactivate = <function> defined @Interface\AddOns\SVUI_!Core\system\dock.lua:485
SetBackdropBorderColor = <function> defined =[C]:-1
Icon = <unnamed> {
}
hover = <unnamed> {
}
pushed = <unnamed> {
}
Sparks = <unnamed> {
}
ClickTheme = <function> defined @Interface\AddOns\SVUITheme_Warcraft\SVUITheme_Warcraft.lua:58
CustomTooltip = <function> defined @Interface\AddOns\SVUI_!Core\system_docklets\garrison.lua:222
SetFrameLevel = <function> defined =[C]:-1
Panel = <unnamed> {
}
MakeDefault = <function> defined @Interface\AddOns\SVUI_!Core\system\dock.lua:464
OrderIndex = 1
BackdropNeedsUpdate = true
}
(*temporary) = "attempt to call method 'StartAlert' (a nil value)"
InCombatLockdown = <function> defined =[C]:-1

AddOns:
Swatter, v5.21c.5521 (SanctimoniousSwamprat)
NPCScan, v6.0.3.5
AchievementsReminder, v
Altoholic, vr152
AskMrRobot, v19
AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
AucStatSales, v5.21c.5521.5476(5.21c/embedded)
AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
Babylonian, v5.1.DEV.332(/embedded)
BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
BittensSpellFlashWarlock, v60000.201502011825
BittensSpellFlashLibrary, v60000.201502011825
BrokerGarrison, v1.6.6
CollectMe, v2.6.2
Configator, v5.1.DEV.376(/embedded)
DailyGlobalCheck, v
DailyGlobalCheckWodRareMobs, v
DailyGlobalCheckWodTreasureChests, v
DailyGlobalCheckWorldBosses, v
DataStore, vr52
DataStoreAchievements, vr38
DataStoreAgenda, vr20
DataStoreAuctions, v6.0.001
DataStoreCharacters, vr30
DataStoreContainers, v6.0.002
DataStoreCrafts, vr64
DataStoreCurrencies, v6.0.002
DataStoreGarrisons, vr8
DataStoreInventory, vr41
DataStoreMails, vr40
DataStorePets, vr36
DataStoreQuests, vr32
DataStoreReputations, v6.0.002
DataStoreSpells, v6.0.002
DataStoreStats, v6.0.002
DataStoreTalents, v6.0.002
DBMCore, v
DBMDefaultSkin, v
DBMInterrupts, v6.0.0b
DBMLDB, v
DBMStatusBarTimers, v
DebugLib, v5.1.DEV.337(/embedded)
Enchantrix, v5.21c.5521 (SanctimoniousSwamprat)
EnchantrixBarker, v5.21c.5521 (SanctimoniousSwamprat)
FollowerLocationInfo, v0.7-beta3
GarrisonMissionManager, vv22
GTFO, v4.35.9
HandyNotes, vv1.3.2
HandyNotesDraenorTreasures, v1.09a
HandyNotesTreasureHunter, v1
Informant, v5.21c.5521 (SanctimoniousSwamprat)
LibExtraTip, v5.12.DEV.363(/embedded)
MasterPlan, v0.25.1
MogIt, v3.4.0
Multishot, v3.1.4
Overachiever, v0.81
RareCoordinator, v
Redprints, vv1.1
Skada, v1.4-28
SkadaForTanks, v50400.1.2
SlideBar, v5.21c.5521 (SanctimoniousSwamprat)
SpellFlash, v6.21
SpellFlashCore, v2.0.5
Stubby, v5.21c.5521 (SanctimoniousSwamprat)
SVUICore, v1.0.0
SVUIActionBars, v1.0.0
SVUIAuras, v1.0.0
SVUIChat, v1.0.0
SVUIInventory, v1.0.0
SVUIMaps, v1.0.0
SVUINamePlates, v1.0.0
SVUIQuestTracker, v1.0.0
SVUISkins, v1.0.0
SVUITooltip, v1.0.0
SVUIUnitFrames, v1.0.0
SVUIThemeSimple, v1.0.0
SVUIThemeWarcraft, v1.0.0
TipHelper, v5.12.DEV.351(/embedded)
WeakAuras, v2.0.9.9
WoWDBProfiler, v
WowheadGarrisonTimer, v1.0.8b
BlizRuntimeLib_enUS v6.0.3.60000 <none>
(ck=e62)

**Comment by failcoder** [comment]
This has been fixed

**Comment by Nyrin** [comment]
awesome can't wait to try it when i get home.
