### ISSUE TITLE
when i did restore defaults on action bars

### ISSUE THREAD

**Issue by Cromaxxx** [failcoder/SVUI-Kit#62]
1x SVUI_ActionBars\Loader.lua:982: attempt to concatenate global 'd' (a nil value)
SVUI_ActionBars\Loader.lua:982: in function <SVUI_ActionBars\Loader.lua:980>
(tail call): ?

[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-60.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
(tail call): ?

[string "safecall Dispatcher[4]"]:9: in function <[string "safecall Dispatcher[4]"]:5>
(tail call): ?
AutoLog\Libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...oLog\Libs\AceGUI-3.0-34\widgets\AceGUIWidget-Button.lua:28: in function <...oLog\Libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:25>

Locals:
nil

**Comment by failcoder** [comment]
Fixed
