### ISSUE TITLE
To be a bug or not a bug...that is the question (grey vendoring and backgrounds)

### ISSUE THREAD

**Issue by hotluck** [failcoder/SVUI-Kit#73]
Hi,

I started using your marvelous addon a few months ago and love it. Until a few days ago I had been using the 5.4.2 version from WoW Interface. I decided to test your new version that is now available on Curse. Now I knew this would mean starting again from scratch, but then I thought that would be a good idea as I was starting to understand the setup more and more.

I removed all bits of SV from the interface folders, and from the wtf folders before re-installing from Curse. Everything seemed pretty ok except I can't seem to get the backgrounds on the unitframes to change (see attached)

![sv background](https://cloud.githubusercontent.com/assets/11139297/6316022/f3d5d7d4-ba0c-11e4-9838-bc3459ac97b6.jpg)

Am I doing something wrong? Which setting should I be changing?

Also, I had the old version set to auto vendor greys which it did perfectly. The new version doesn't do it even though I have checked that the flag is ticked against it. I do use Ark Inventory for my bags so always had the bag options disabled. I noticed there isn't a disable option in this new one so does this mean I need to remove the SV Inventory module or is that including more than just bag details?

Amanda

**Comment by failcoder** [comment]
Try the latest version from curse and see if these are still an issue

**Comment by hotluck** [comment]
Grey vendoring works beautifully now thank you :)

As to the backgrounds on the untiframes, they still won't change. I have changed the textures in the General Options but the unti frames still look the same as in the pic above. Is there another place they need changing that I am missing?

**Comment by failcoder** [comment]
You want to use the options located under UnitFrames->General->Unit Backgrounds

**Comment by hotluck** [comment]
I tried that too and it still didn't change. I have tried with both 3D and 3D overlay and the backgrounds don't change on either. Very weird!

_EDIT_ Also since installing the new version from curse this morning, the grey vendoring is not working again. Sorry :(

**Comment by failcoder** [comment]
Both backdrops and auto censoring updated in latest patch

**Comment by hotluck** [comment]
Brill. I am one happy bunny with both things working. Thank you :)

**Comment by hotluck** [comment]
Since latest version, I noticed that the UnitFrames/General Backgrounds were showing as blank. When I selected another background, it gave the following error and didn't do anything (both unit and small unit) -

Date: 2015-03-03 15:10:17
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\SVUI_!Options\UnitFrames.lua line 2427:
   attempt to index field '?' (a string value)
Debug:
   (tail call): ?
   SVUI_!Options\UnitFrames.lua:2427:
      SVUI_!Options\UnitFrames.lua:2426
   (tail call): ?

   [string "safecall Dispatcher[2]"]:9:
      [string "safecall Dispatcher[2]"]:5
   (tail call): ?
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:799:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614
   (tail call): ?

   [string "safecall Dispatcher[3]"]:9:
      [string "safecall Dispatcher[3]"]:5
   (tail call): ?
   Ace3\AceGUI-3.0\AceGUI-3.0.lua:314: Fire()
   ...s\AceGUI-3.0-SharedMediaWidgets\BackgroundWidget.lua:23:
      ...s\AceGUI-3.0-SharedMediaWidgets\BackgroundWidget.lua:21
Locals:
None

**Comment by failcoder** [comment]
This concerns me a lot :(
Can you possibly send or pastebin a copy of your global saved variables file?

**Comment by hotluck** [comment]
The SVUI_!Core.lua is a little big to post in here. If you want to PM an email address to hotluck on WoWInterface, I can attach it to an email for you.

**Comment by failcoder** [comment]
Ok so I made some changes that I hope will fix your issue. Curse and WowInterface have been updated

**Comment by hotluck** [comment]
They were still showing as blank and gave the following error -

Date: 2015-03-05 11:28:41
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\SVUI_!Options\UnitFrames.lua line 2433:
attempt to index field '?' (a string value)
Debug:
(tail call): ?
SVUI_!Options\UnitFrames.lua:2433:
SVUI_!Options\UnitFrames.lua:2432
(tail call): ?

[string "safecall Dispatcher[2]"]:9:
[string "safecall Dispatcher[2]"]:5
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:799:
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614
(tail call): ?

[string "safecall Dispatcher[3]"]:9:
[string "safecall Dispatcher[3]"]:5
(tail call): ?
...\AddOns\SVUI_!Options\libs\AceGUI-3.0\AceGUI-3.0.lua:314: Fire()
...s\AceGUI-3.0-SharedMediaWidgets\BackgroundWidget.lua:23:
...s\AceGUI-3.0-SharedMediaWidgets\BackgroundWidget.lua:21
Locals:
None

I did some investigating by looking in the wtf file and found that under SVUI_Media, there is no profile for Main Level (100) which is the profile I am using so I think this is causing the error. This is probably from the various other profile problems I have been testing and you have fixed. I think the data has just got corrupted. I could just copy that bit from one of the other profiles but that could cause more problems, so I am just going to delete the wtf files and start again from scratch (you've done so many fixes and changes since I first did it that it's the best option I think).

I'll let you know when I've done it. :)

**Comment by hotluck** [comment]
Well starting from scratch did the trick. I was able to change the unitframes without errors and the greys are still vendoring. The problems I did find are more in connection with the other issue I have open to do with profiles so I shall add the details against that one.

**Comment by hotluck** [comment]
Oops...forgot to close this one hehe
