### ISSUE TITLE
[Bug] Inventory with phantom item sparks

### ISSUE THREAD

**Issue by penguinsane** [failcoder/SVUI-Kit#76]
After sorting my inventory, the little item "sparks" stick around till /reload: http://puu.sh/gbYwI/4bbb87ee21.jpg

**Comment by failcoder** [comment]
Yeah I see this happening. I'm looking into it now. Any idea if 6.1 had any animation updates I may not be aware of?

**Comment by penguinsane** [comment]
I'm not entirely sure, but I didn't see it happening in the updates prior to the one that fixed the frame taint issue with the dungeon journal/follower journal you pushed last night.

**Comment by penguinsane** [comment]
Confirmed fixed. Thank you!
