### ISSUE TITLE
Henchman + error

### ISSUE THREAD

**Issue by Cromaxxx** [failcoder/SVUI-Kit#8]
henchmen button doesnt work at all and dock for skada is gone got this error when i click henchman and when i try to create dock for skada

```
3x SVUI_Tooltip\SVUI_Tooltip-1.0.0.lua:522: attempt to index field 'LootCache' (a nil value)
SVUI_Tooltip\SVUI_Tooltip-1.0.0.lua:522: in function <SVUI_Tooltip\SVUI_Tooltip.lua:512>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...ns\TradeSkillMaster\Libs\LibExtraTip\LibExtraTip.lua:387: in function `SetHyperlink'
SVUI_Chat\SVUI_Chat-1.0.0.lua:1090: in function <SVUI_Chat\SVUI_Chat.lua:1084>

Locals:
(*temporary) = <function> defined =[C]:-1
 = <function> defined @TradeSkillMaster\Libs\LibExtraTip\LibExtraTip.lua:426
 = <function> defined @SVUI_Tooltip\SVUI_Tooltip.lua:512
```

some conflict with tsm ... still font stats on stats panel as u can see on 
http://i.imgur.com/pJPybKy.jpg

**Comment by failcoder** [comment]
Fixed

**Comment by failcoder** [comment]
Also, regarding the font size, you can change it under Fonts (see screenshot)
http://imgur.com/rYPaF9Q

**Comment by Cromaxxx** [comment]
ok thnx also keybinds not showing for some reason and skada dock button is green, henchman button is between skada and quest dock http://imgur.com/qERlNF5, also theres no action bars tab in svui config window so you cant configure them..

**Comment by Cromaxxx** [comment]
and under plugins it doesn't show plugins at all

**Comment by ghost** [comment]
Cromaxxx something must be messed up in your install if your not seeing any action bar options in the config because it's all there.  and you can move the henchman button so it's not between by alt+clicking the buttons

**Comment by Cromaxxx** [comment]
i deleted all folders and tried /svui reset get the error

1x SVUI_!Core\system\core.lua:556: attempt to index local 'self' (a nil value)
SVUI_!Core\system\core.lua:556: in function `?'
SVUI_!Core\system\slash.lua:73: in function`?'
FrameXML\ChatFrame.lua:4387: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4041: in function`ChatEdit_SendText'
FrameXML\ChatFrame.lua:4080: in function <FrameXML\ChatFrame.lua:4076>
[C]: in function `ChatEdit_OnEnterPressed'
[string "_:OnEnterPressed"]:1: in function <[string "_:OnEnterPressed"]:1>

Locals:
msg = "reset"
lower = <function> defined =[C]:-1
trim = <function> defined =[C]:-1
SVUI_SLASH_COMMANDS = <table> {
 move = <function> defined @SVUI_!Core\system\layout.lua:1200
 pvp = <function> defined @SVUI_!Core\system\reports.lua:559
 reset = <function> defined @SVUI_!Core\system\core.lua:550
 bg = <function> defined @SVUI_!Core\system\reports.lua:559
 install = <function> defined @SVUI_!Core\setup\installer.lua:893
}
type = <function> defined =[C]:-1
SV = <table> {
 defaults = <table> {
 }
 UnregisterUpdate = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:659
 HexColor = <function> defined @SVUI_!Core\system\media.lua:404
 filterdefaults = <table> {
 }
 class = "PALADIN"
 ResetData = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:973
 NewAnchor = <function> defined @SVUI_!Core\system\layout.lua:1192
 Skins = <table> {
 }
 CHAT_MSG_COMBAT_FACTION_CHANGE = <function> defined @SVUI_!Core\system\automations.lua:186
 RegisterFonts = <function> defined @SVUI_!Core\system\media.lua:610
 PostLoaded = true
 ___eventframe = <unnamed> {
 }
 PLAYER_REGEN_DISABLED = <function> defined @SVUI_!Core\system\core.lua:747
 QUEST_PROGRESS = <function> defined @SVUI_!Core\system\automations.lua:257
 ConfigurationMode = false
 ReLoad = <function> defined @SVUI_!Core\system\core.lua:790
 PreLoad = <function> defined @SVUI_!Core\system\core.lua:796
 ImportProfile = <function> defined @SVUI_!Core\system\core.lua:575
 Sounds = <table> {
 }
 GlobalFontList = <table> {
 }
 db = <table> {
 }
 Credits = "|cffff9900SUPERVILLAIN CREDITS:|r
|cff4f4f4f---------------------------------------------|r
|cffff9900CREATED BY:|r  S.Jackson
|cff4f4f4f---------------------------------------------|r
|cffff9900CODE GRANTS BY:|r  Azilroka, Sortokk, Kkthnx
|cff4f4f4f---------------------------------------------|r

|cffff9900SPECIAL THANKS TO:  |r|cfff81422Cairenn|r |cff2288cc(@WowInterface.com)|r  ..the most patient and accomodating person I know!

|cffff9900A VERY SPECIAL THANKS TO:  |r|cffffff00Movster|r  ..who inspired me to bring this project back to life!
|cff4f4f4f---------------------------------------------|r

|cffFFFF00THE HIGH COUNCIL  (aka EXECUTIVES):|r
|cff33FF33DOONGA|r - (The man who keeps me busy)
|cff33FF33PENGUINSANE|r - (The ace up my sleeve)
|cff4f4f4f---------------------------------------------|r

|cff99ff33KINGPINS  (aka INVESTORS):|r
Movster, Meggalo, Penguinsane, FaolanKing, Doonga
Cazart506, Moondoggy, Necroo, Chief Pullin, lkj61
BloodEagle, Egbert, Jerry Ferguson, Hyti, Elton
James Wats Reports = <table> {
 }
 Options = <table> {
 }
 Dock = <table> {
 }
 GetTheme = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:906
 ClassRole = "M"
 HasErrors = true
 Version = "1.0.0"
 TaintHandler = <function> defined @SVUI_!Core\system\core.lua:782
 DebugMode = true
 Timers = <table> {
 }
 UI_SCALE_CHANGED = <function> defined @SVUI_!Core\system\api.lua:1255
 Media = <table> {
 }
 ResetAnchors = <function> defined @SVUI_!Core\system\layout.lua:1208
 NewModule = <function> defined @SVUI_!Core\libs_SVUI_Lib\Registry.lua:921
 ConfigID = "SVUI_!Options"
 YOUR_HENCHMEN = <table> {
 }
 ToggleHenchman = <function> defined @SVUI_!Core\system\henchmen.lua:469
 AddonMessage = <function> defined @SVUI_!Core\system\core.lua:515
 Allegiance = "Alliance"
 Events = <table> {
 }
 RollFrames = <table> {
 }
 SpecialFX = <table> {
 }
 Inventory = <table> {
 }
 NoTexture = "SVUI_!Core\assets\textures\EMPTY"
 L = <table> {
 }
 AFK = SVUI_AFKFrame {
 }
 GameVersion = 60000
 AutoQuestProxy = <function> defined @SVUI_!Core\system\automations.lua:210
 VersionCheck = <function> defined @SVUI_!Core\system\

**Comment by Cromaxxx** [comment]
deleted all lua from svui in wtf and folders again.. nope still not action bar tab and /sv kb command opens henchman does nothing http://i.imgur.com/tr2muaM.jpg

**Comment by failcoder** [comment]
one more update, try again

**Comment by Cromaxxx** [comment]
still not showing keybinds on buttons even though now /sv kb does work, still no action bar tab in config so i can customise bars like 2 rows of 6 buttons..  i can use only and use standard adjust bars options that works.. thats f strange

**Comment by Cromaxxx** [comment]
tried turning off plugins individually from addons and nothing helps unless i turn off all svui..then numbers on buttons come back.. its something with svui core not calling svui action bars properly

**Comment by ghost** [comment]
Well I just got this issue in the latest update as well .-.

Edit: It looks like this is the last commit (2fbce8e05ae86a8be29d3cf63cc1854d2b654538) that actually worked with the action bars showing up in the config. 

Cromaxxx try going back to the commit I just posted (if you know how) and see if the action bar stuff shows up in the config for you as well.

**Comment by Cromaxxx** [comment]
i tried every update there was today

**Comment by ghost** [comment]
when you update or go back updates do you delete the folders before putting in the new ones cromaxxx? delete everything to do with SVUI and go back to the above commit I posted and the action bar stuff should be there then set it up how you like and then you should be able to go back to the update that recently happened and everything should stick for the time albeit the options will be gone for the time being until mung or failcoder can get it figured out completely.

**Comment by Cromaxxx** [comment]
i used this ui from 3.8 version i know that i need delete everything.. and yes on that commit action bars work.. so there is something wrong with latest update

**Comment by failcoder** [comment]
Fixed

**Comment by ghost** [comment]
Can confirm that it is fixed, go ahead and close it cromaxxx if it's fixed for you as well.
