### ISSUE TITLE
Pala spell issue

### ISSUE THREAD

**Issue by hotluck** [failcoder/SVUI-Kit#81]
Using my pala for the first time with this version and I noticed 2 things with the Consecration spell. 

The first is that the "buff/debuff" button shows up in the totem bar. 

The second is that you cannot loot your kill until the consecration has finished or if you click once to end it before the time runs out. I did remove SV from my addons just to check if it was a problem with Blizzard in 6.1 but Consecration works correctly then. _EDIT_ To be more precise you just can't use your mouse while Consecration is active for moving or otherwise, but you can move with the keyboard...if that helps :)

**Comment by failcoder** [comment]
This was fixed
