### ISSUE TITLE
Big profile/font problems ( r20150301050251 curse version)

### ISSUE THREAD

**Issue by hotluck** [failcoder/SVUI-Kit#85]
I installed the new version and when I logged into my chars they were no longer on the custom profiles I had created. They had gone back to defaults. The weird thing is that when I had finished setting up my chars on one server for my first account, I removed all the default profiles and left just the 2 profiles I had set up with the first version from Curse. This was so I could copy the files across to my other account and use the same profiles, which worked perfectly at the time.
So when I went to select one of those 2 profiles in the Link to box, it was showing all the default profiles that I had deleted before. Also when I changed the profile, it reset alot of stuff back correctly except some fonts. Not sure if anything else hasn't worked or not. Anyway, when I changed some fonts again and went back to the profile screen, it was still showing the default profile and not my custom profile in the copy to and link to boxes.
As I hadn't been on the other account since the first installation on Curse except to use my new custom profiles, I thought I'd copy those wtf files back to my main account. The profile screen then showed all the default profiles from the other account but not the ones from my main account, however it was still not changing/keeping my custom profiles when I changed them.

I hope this makes sense to you.

**Comment by failcoder** [comment]
Major update to profiles. Try latest and let me know

**Comment by hotluck** [comment]
I re-copied my wtf files from my other account first and logged into my main char. I then selected one of my custom profiles. Everything came through except fonts and some action bar changes. I went through and set the fonts and action bars and they stayed. I logged out and back into the char and they were still setup correctly. The profile is still showing as my custom profile in the Copy To and Link To boxes as well which is good.

I then logged into another char and set it to the same custom profile as the main char. It hadn't saved the changes to the profile (or the code is not picking up the changes).

P.S. I know some people find this very annoying but I have been a software tester for over twenty years so I know these things take time to sort. I'm happy to keep on testing your addon because to be quite honest, you have done an amazing job with it and I love it :)

_EDIT_ I just thought about checking the wtf file to see what fonts were showing in that. I found that the fonts had changed, but in the main char default profile, not the custom one. The unitframe backgrounds etc. that I tested for the other bug were also changed in the original profile, not the custom one. I also found that the fonts etc that I had set up in the original setup are still there under the custom profile so the code is not picking them up when the profile is selected. Hope this helps.

**Comment by failcoder** [comment]
By chance did the second character have dual spec switching enabled?

**Comment by hotluck** [comment]
Damn you're quick lol...I was just putting an edit in my previous comment that might help...and no I haven't set up any dual spec stuff yet on any char. I have left those as they were when I went through the start setup screens.

**Comment by failcoder** [comment]
Just updated curse, check this again when you can. Thank you :)

**Comment by hotluck** [comment]
Ok, I went into my main char. I selected another profile to Link to. It asked if I really wanted to link to this other profile. When I clicked on Yes, it did nothing. I did it again, and this time it changed the 2 boxes to show the newly selected profile but it didn't reload the gui. I tried changing it back to the original profile and again it didn't change until I did it twice and it still didn't re-load the gui.

Would having a copy of my core wtf file help you?

_EDIT_ When you log out and back into the character it does pick up all the details of the profile shown in the profile boxes

_EDIT_ 2 - If you log onto a char, select a new profile just once (when it doesn't show the new profile in the boxes), log out and back in, it has actually changed to the profile you had selected and does show it in the profile boxes. 

On a positive note, it is correctly saving font changes made to a profile on a char because they are being picked up when selected on another char.

**Comment by hotluck** [comment]
1) Deleted all SVUI lua files from the wtf and subfolders
2) All addons enabled except Inventory as I use ArkInventory for my bags.
3) I went into my first char Jay and went through the auto install screens.
4) Moved frames around to how I wanted, changed General options changed ok.
5) Font 3 re-loads on first fonts changed from  default to Aorel.as expected.
6) Docks, actionbars and chat changed correctly.
7) Maps - unticking the minimap xy co-ord does not remove them, If you log oand back in, it has removed them.
8)Tooltip - talent spec is showing as unticked but talents are showinf on the tooltips.

Part way through changing the fonts, I realised I hadn't created a new Main Level (100) so I created a new profile and saved it. I then carried on making my changes which looked good when I had finished. 

I then logged onto my second char. It too went though the installation process. I then selected the profile to Main Level 100 and re-loaded. I still showed the char default so I logged out and back in. The profile was now showing Main Level (100). However the only changes on the screen are the ones before I first created the Main Level (100). Nothing I changed after that has saved to that profile.

I logged back on Jay and thoses were also not showing changes made after first creating the profile.

I quickly looked in the wtf files but nothing stood out. If you need the new lua files, just let me know and I will email them to you. :)

**Comment by hotluck** [comment]
I was starting to fall asleep when I was doing the last part. Now I'm properly awake, I've looked at the account core file again. Even though I had created a new profile a short way through making font changes, it appears that all changes made after that still saved to Jay's original default profile.

I know when I first started using classic SVUI, you made all your changes and then saved it, but I recall this being changed so that any changes where automatic and would automatically be picked up by chars using the same profile. Is the new version still using the latter option?

_EDIT_ After a painfully long lack of power I decided to have another go at that core file. I wish I hadn't now because I confused myself. NOTE TO SELF: Never try and investigate code and data when you have a house full of electricians, naughty children, and a partner with manflu lol. No good comes of it.

I'll wait and see what you find...good luck :)

**Comment by failcoder** [comment]
I just pushed changes that include shiny new profile script! I tested the bejeezus out of it and it's ready to roll. Let me know what you find.

**Comment by hotluck** [comment]
Looking good now. Only 1 minor thing went wrong -

1) Logged on Jay and changed all the fonts and stuff that it hadn't picked up before. Worked perfectly.
2) Logged on another 100 char that I had tried setting to the 100 profile yesterday and it picked up everything too...perfect.
3) Logged another 100 char that hadn't been set up at all, went through the install procedures and when completed, I changed to the 100 profile. Worked perfectly.
4) Logged a non 100 char, and used the Copy From facility to get the 100 profile. Worked Perfectly.
5) Created a new non 100 profile at that point. Still good.
6) Made changes to only the bottom stats in the Dock tab. Worked good.
7) Logged onto another non 100 char that hadn't got any settings. Went through the install procedures and then selected the non 100 profile. It hadn't saved the Dock changes.
8) Logged back on the non 100 char I had created the profile on. The Dock changes weren't there either.
9) Exited the game.
10) Went back in the game to the first non 100 char and made the changes to the Dock screen again.
11) Logged out of the char and back in. Dock changes were there this time.
12) Logged onto the 2nd non 100 char and the changes were there too.

There seems to be a problem with data being saved while still in the game after creating a new profile. Could it be that it doesn't register the changes in a new profile until you have exited the game first?

**Comment by hotluck** [comment]
Not sure what exactly you changed in the latest version (after I did that test) but alot of the fonts have now disappeared including Aorel Sans Black which I was using.

_EDIT_ I just tried to change the font on a non SVUI addon and now the SVUI fonts aren't showing there, so you can see SVUI font's only in SVUI and I'm guessing it's non-Blizzard and non-SVUI fonts that can't be seen in SVUI. Same goes for backgrounds too.

**Comment by failcoder** [comment]
There are issues with the shared media library that I am currently working on

**Comment by hotluck** [comment]
No problem...it's not like they are major problems stopping me from playing. I'd rather you took your time sorting it than doing it quickly and making a mess of it :)

**Comment by hotluck** [comment]
I've just installed  r20150309044529 and everything looks ok except it's not picking up the bottom stats again in the Dock screen. I don't use the top ones so I don't know if that's a problem too.

**Comment by failcoder** [comment]
Dock stats just got reset due to a change.

**Comment by hotluck** [comment]
Ok, thanks, I'll set that up again :)
