### ISSUE TITLE
Experience error stopping lower bars showing

### ISSUE THREAD

**Issue by hotluck** [failcoder/SVUI-Kit#86]
On my chars that are not 100, I show Experience in the Bottom Stats. After the latest update, I get a problem with the following error appearing -

Reports [Load]: @(03/01/15 15:48:06) - ...ace\AddOns\SVUI_!Core\system_reports\experience.lua:48: attempt to compare number with nil

At first I thought it was because my char had just gone up a level yesterday, but I loaded another char who isn't 100 and they also get the error.

Because of this error, none of the other Bottom Stats will show.

**Comment by failcoder** [comment]
Fixed

**Comment by hotluck** [comment]
Yep, you definitely have done that. Thank you :)
