### ISSUE TITLE
[Bug] Quest tracking not clearing upon quest complete

### ISSUE THREAD

**Issue by penguinsane** [failcoder/SVUI-Kit#87]
Sometimes it seems like the quest tracker isn't clearing properly when the quest is completed, resulting in a quest being "phantom-tracked" until clicked off and onto another. This results in the highlighted quest areas on the minimap still showing, even though the quest has been completed and turned in already.

Minor issue.

**Comment by failcoder** [comment]
Is this happening for general objective lines, or on "active/tracking" lines?

**Comment by penguinsane** [comment]
This is happening for the active/tracking lines, though those quests that are active/tracked that don't clear also appear in the general objective lines.

**Comment by failcoder** [comment]
Just updated curse, check this again when you can. Thank you :)

**Comment by penguinsane** [comment]
Oops! Could have sworn that I commented sooner.

Took it for a spin through some dailies, looked good. Thanks for the quick update! I'll let you know if any other weirdness happens. :)

**Comment by penguinsane** [comment]
lol, I went to do DMF dailies and am running into this issue again. I'm starting to think that the DMF just does not like SVUI!

Reopening. Take a toon for a spin through the DMF game dailies, you should see what's happening. It's like it's just not clearing active/tracked after turning in. Highlighted minimap areas not clearing, same as before.

**Comment by failcoder** [comment]
This issue was moved to failcoder/Supervillain_UI#103
