### ISSUE TITLE
[Bug] Top statistics overlapping pet battle; pet health bars not coloring on rarity

### ISSUE THREAD

**Issue by penguinsane** [failcoder/SVUI-Kit#88]
http://puu.sh/givm4/48d531b269.jpg

This has happened previously, is happening again, lol. Previously, you removed the top statistics in pet battles. Could also lower the pet battle frames a smidge, if possible.

Also, as seen in screenshot, health bars aren't coloring on rarity. Intended? They used to.

**Comment by failcoder** [comment]
Fixed, though I don't remember coloring the health bar itself according to rarity

**Comment by penguinsane** [comment]
Then that may have been in error. I do remember that sometimes my "rare" pets had dark blue health bars, and sometimes the gray ones for common ones, but it really seemed spotty. So it's possible that was an error back then. I haven't pet battled much, just the DMF faire, but I will try to get some done soon to see if it's still doing it.

Will verify tomorrow when I'm able to log in. Thank you!

**Comment by penguinsane** [comment]
Confirmed. Thanks a bunch!
