### ISSUE TITLE
[Bug] Darkmoon prize bags still appearing behind bag frame

### ISSUE THREAD

**Issue by penguinsane** [failcoder/SVUI-Kit#89]
This has been an ongoing issue that I probably bring up every DMF, I'm sorry! It seems that these three things are the only items that have this sort of issue, I'm not sure why. It MAY be because they drop a currency that goes into the Currency tab?

http://www.wowhead.com/item=93724/darkmoon-game-prize
http://www.wowhead.com/item=91086/darkmoon-pet-supplies
http://www.wowhead.com/item=116062/greater-darkmoon-pet-supplies

Every time you open one of these, the "what's in the box" frame appears behind the bag frame, so you can't click the items out of it individually. Such as, for example, saving the boxes for the hats (which has been hotfixed I think, but still).

**Comment by failcoder** [comment]
This issue was moved to failcoder/Supervillain_UI#102
