### ISSUE TITLE
[idea] combat indicator and layout 

### ISSUE THREAD

**Issue by Vyntrox** [failcoder/SVUI-Kit#9]
what about a nicely looking combat indicator. not this small little fist :)
can't find my code a the moment... but is basically a nice texture that swipes in from left or right an remains in the topmost corner as soon as the fight starts.
combined with a combat clock or a time to death thingy that whould be awesome an unique, except mine.

it's one of my oldy projects but never had the time to finish it. 
absolutely basic but nice idea
http://www.wowinterface.com/downloads/info22603-oUF_BeatEmUP.html

i know it's part of elvui but... i love this little feature the set a texture behind the chatbox. whould be nice to see it in your ui too :)

**Comment by TheBloodEagle** [comment]
As a fan of minimalism, I like the little fist or !, as it lets me know what is happening, but is not too huge or in my face. If you do add this Mung, please allow an option for either/or?

Good idea though

**Comment by failcoder** [comment]
OMG I didn't realize tht was your addon! I loved that one, in fact it inspired a few aspects of SVUI. Whats even funnier is that if your look here (https://github.com/failcoder/SVUI-Kit/tree/master/SVUI_!Core/assets/textures) that VS.blp file... is yours HA! The image has been floating around SVUI folders for a long time, but I still haven't actually used it because I never got around to asking for permission. BAD MUNGLUNCH!

**Comment by Vyntrox** [comment]
nice to hear that my layout gave you some ideas for your awesome ui.
oh and btw i posted the idea with the hearthstone button too.

permission granted!

Would be nice to see my Name in the Credits :)

**Comment by failcoder** [comment]
Oh damn! I am so sorry I completely forgot to add your name before when you suggested the hearth button! I get steam rolled by coding and forget stuff ALL THE TIME, I just need reminders occasionally. 

Regardless, I just added your name to the contributor credits.

**Comment by Vyntrox** [comment]
I wish that I could help more but my skills in lua got rusty over time. More into designing in my sparetime at the moment.

**Comment by failcoder** [comment]
This issue was moved to failcoder/Supervillain_UI#89
