### ISSUE TITLE
Altoholic not skinning

### ISSUE THREAD

**Issue by angryfatkid** [failcoder/SVUI-Kit#90]
This release (and previous) have not skinned Altoholic for me.  Please let me know if you need anything else.

![wowscrnshot_030215_194725](https://cloud.githubusercontent.com/assets/10525022/6455959/8432e0f8-c118-11e4-93e0-210d349d47d1.jpg)

**Comment by failcoder** [comment]
Dafuq?

**Comment by failcoder** [comment]
Ok thanks I'll check it out

**Comment by angryfatkid** [comment]
Thanks!   It also happens with Ackis Recipe List...but I seem to recall that addon may not be skinnable.

**Comment by failcoder** [comment]
This issue was moved to failcoder/Supervillain_UI#90

**Comment by failcoder** [comment]
This issue was moved to failcoder/Supervillain_UI#101
