### ISSUE TITLE
Mini-map query

### ISSUE THREAD

**Issue by hotluck** [failcoder/SVUI-Kit#92]
Before I started using SVUI, one of the addons I used to use was SexyMaps. Now I can't remember whether this was something the standard Blizzard mini-map did as well (not used it in such a long time lol), however it used to show where you were. For example if I was in Camp Oneqweh, it would show that on the mini-map. Using the SVUI version, it shows everywhere in Grizzly Hills as Grizzly Hills. If I need to confirm where I am, I have to check the normal map which is frustrating. Is this easy to change/fix?

**Comment by failcoder** [comment]
I never noticed this, you are right. I will get this updated.

**Comment by hotluck** [comment]
Thanks Mung :)

**Comment by failcoder** [comment]
This issue was moved to failcoder/Supervillain_UI#100
