### ISSUE TITLE
Slider problems

### ISSUE THREAD

**Issue by hotluck** [failcoder/SVUI-Kit#93]
I was showing my daughter the setups for your addon on one of her characters. She tends to grab onto me while she's watching which makes it very hard from me to get the sliders in the correct place (such as dock widths, etc.), so I thought I'll just click on the number underneath and manually change the number. Doesn't work. No matter what you enter, the slider will still stay at the original number. The number will only change and stay if you move the slider. I tried various ones on various screens and they were did the same.

**Comment by failcoder** [comment]
This issue was moved to failcoder/Supervillain_UI#99
